language: java

# workaround for broken openjdk7
sudo: required # for setting hostname
addons:
  hostname: localhost
before_install:
- cat /etc/hosts
# end

jdk:
  - oraclejdk7
  - openjdk8
  - oraclejdk8
  - openjdk8
  - oraclejdk9

script:
  - ./gradlew clean build javadoc
